---
project: lambdas
default-region: us-east-1
code-bucket: parsely-lambda
apps:
  - gordon.contrib.lambdas
  - gordon.contrib.helpers
  - app

#kinesis:
#  kinesis_integration:
#    lambda: app.lambda_stream
#    stream: ref://KinesisARN
#    batch_size: 1
#    starting_position: LATEST
